name: Python linting
on:
  push:
    branches:
      - develop
      - 'release/*'
  pull_request:
    branches:
      - develop
      - 'release/*'
  workflow_dispatch:

defaults:
  run:
    shell: bash
jobs:

  python_linter:
    name: Python unittests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip netcdf-bin
          sudo pip3 install pylint==2.16

      # Run python unittests
      - name: Lint the test directory
        run: |
          ./manage_externals/checkout_externals workflow-tools
          export PYTHONPATH=$(pwd)/ush:$(pwd)/ush/python_utils/workflow-tools:$(pwd)/ush/python_utils/workflow-tools/src
          pylint --ignore-imports=yes tests/test_python/
          pylint ush/create_*.py
          pylint ush/generate_FV3LAM_wflow.py
