name: Python unittests
on:
  push:
    branches:
      - develop
      - 'release/*'
  pull_request:
    branches:
      - develop
      - 'release/*'
  workflow_dispatch:

env:
  UNIT_TEST: True

defaults:
  run:
    shell: bash
jobs:

  python_unittests:
    name: Python unittests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip netcdf-bin
          sudo pip3 install pyyaml jinja2==2.11 f90nml
          sudo pip3 install numpy matplotlib basemap

      # Run python unittests
      - name: Run python unittests
        run: |
          ./manage_externals/checkout_externals ufs-weather-model workflow-tools
          # exclude test_retrieve_data that is tested in functional test
          export PYTHONPATH=$(pwd)/ush:$(pwd)/ush/python_utils/workflow-tools:$(pwd)/ush/python_utils/workflow-tools/src
          python3 -m unittest -b tests/test_python/*.py

