name: Python functional tests
on:
  push:
    branches:
      - develop
      - 'release/*'
    paths:
      - ush/*retrieve_data.py
      - parm/data_locations.yml
  pull_request:
    branches:
      - develop
      - 'release/*'
  workflow_dispatch:

env:
  CI: true

jobs:
  python_functests:
    name: Python Functional Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip netcdf-bin
          sudo pip3 install pyyaml

      # Run python functional tests
      - name: Run python functional tests
        run: |
          export PYTHONPATH=${PWD}/ush
          python3 -m unittest -b tests/test_python/test_retrieve_data.py
